### ISSUE TITLE
Login and register button not accessible on mobile devices without closing keyboard

### ISSUE THREAD

**Issue by coperator** [auth0/lock#1619]
### Description

Since Lock version 11.12 and the changes introduced with #1539 the login and register buttons are not accessible anymore on mobile devices, if the user has the keyboard open. The user is forced to close/hide the keyboard first.

The behavior is demonstrated in this video:  
![ezgif-2-76ddb617957e](https://user-images.githubusercontent.com/7254523/54271841-99358f80-4582-11e9-9918-37230a43065d.gif)

The video shows our login page with small style modifications. The described problem is independent of this modifications.

Before the style change, i.e. with 11.11, the user was always able to scroll down to the buttons, although the buttons were initially offscreen (issue #1474)

### Environment

We tested this with

* Lock version: 11.12 and up
* Browser version: Mobile Firefox 64.0.2, Chrome 71.0.3578.99
* OS: Android

**Comment by coperator** [comment]
Maybe somehow related to issue #1609. However, here we are on mobile view, there its on tablet with whole widget affected.

**Comment by luisrudge** [comment]
@coperator we just merged #1621 that fixes a bunch of mobile visualization issues. Can you try the master branch to see if they fix your issue? I just tested here and it seems to be working:

![scroll](https://user-images.githubusercontent.com/941075/54448947-bc4f7300-472b-11e9-9340-603e9ee90cd4.gif)

This will be released on Monday

**Comment by d3vhound** [comment]
Was this ever released? Still having issues with password-less hosted login.
![Image from iOS](https://user-images.githubusercontent.com/17565159/59241699-50679400-8bce-11e9-9da6-2ff3a5d09e83.png)

**Comment by luisrudge** [comment]
@d3vhound what version are you using?

**Comment by fsc7** [comment]
New version, having the same problem on Samsung Galaxy 6

**Comment by ahujamanish** [comment]
We're facing similar issues at our end. The submit button is hidden behind the keyboard and the user has to either scroll the whole content or dismiss the keyboard manually to be able to access it. @luisrudge can you confirm if the changes you shared above are merged and available?

**Comment by stevehobbsdev** [comment]
@ahujamanish This should now be fixed in the latest version of the library - can you give it a try?
