### ISSUE TITLE
following parameters are not allowed on the `/authorize` endpoing: [popup,popup_options,sso]

### ISSUE THREAD

**Issue by Amialc** [auth0/lock#951]
Lock throws warning even if `sso`, `popup` or `popup_options` are not set.
Same issue as https://github.com/auth0-samples/auth0-jquery-samples/issues/28, https://github.com/auth0-samples/auth0-javascript-samples/issues/1 and https://github.com/auth0-samples/auth0-react-samples/issues/1. Creating duplicate here because seems it's because lock send this options even if they are not set.

- Code snippet or sample project that reproduces the bug
```
var lock = new Auth0Lock(AUTH0_CLIENT_ID, AUTH0_DOMAIN, {
    oidcConformant: true,
    autoclose: true,
    auth: {
      redirectUrl: AUTH0_CALLBACK_URL,
      responseType: 'token id_token',
      audience: 'https://' + AUTH0_DOMAIN + '/userinfo'
    }
  });
```
- Screenshots when appropriate
![screenshot](https://cloud.githubusercontent.com/assets/1114365/23702068/5e39813e-0402-11e7-8d53-933c5dc353f3.png)
- Lock version - 10.11 (using 10.13 warning says only about one parameter `sso`, 
[screenshot](https://cloud.githubusercontent.com/assets/1114365/24365166/ac350ea6-131d-11e7-8594-7ceccfeea221.png))

- Browser & OS - Chrome  56.0.2924.87, Windows.

**Comment by hzalaz** [comment]
This is not a Lock issue and is a warning that can be ignored. We will evaluate how to proceed with this in auth0.js

**Comment by dentarg** [comment]
> This is not a Lock issue and is a warning that can be ignored. We will evaluate how to proceed with this in auth0.js

Was address recently in https://github.com/auth0/auth0.js/pull/611

@hzalaz @luisrudge do you know when you will release a Lock version with updated auth0-js?

**Comment by luisrudge** [comment]
@dentarg next week

**Comment by luisrudge** [comment]
@msteckyefantis what version are you using?

**Comment by msteckyefantis** [comment]
@luisrudge I'm using auth0-js version 8.12.2

**Comment by luisrudge** [comment]
@msteckyefantis this was fixed in 9.0.2: https://github.com/auth0/auth0.js/blob/master/CHANGELOG.md#v902-2017-12-29

**Comment by msteckyefantis** [comment]
I notice there is a warning on the npm module itself:

```
Auth0.js v9 uses our latest embedded login API. This version cannot be used inside Auth0-Hosted Login Pages. If you are using a Hosted Login Page, keep using Auth0.js v8.
```
I am using auth0js on my own page, but it gets redirected to the hosted login page.

is it okay for me to use auth0js v9 for my website (not on the hosted login page)?

**Comment by takahser** [comment]
@luisrudge FYI this still happens in various versions, such as 9.0.2, 9.4.1 as well as 9.6.0 (I only tested those).

**Comment by victoriafrench** [comment]
I am seeing this on 11.6.1 and I am using the hosted auth0 template.

**Comment by jShaf** [comment]
Same here with 11.14.1

**Comment by cdownie** [comment]
Happening to us with auth0-js 9.10.1

Following parameters are not allowed on the `/authorize` endpoint: [sso]

**Comment by victoriafrench** [comment]
seeing this on 11.20.3 using hosted page. warning is for params `sso` and `is_submitting`

**Comment by victoriafrench** [comment]
ok scratch that, it appears these params are coming directly from auth0 and are being set by using `config.internalOptions` as shown:

```js
var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
     auth: {
          redirectUrl: config.callbackURL,
          responseType: (config.internalOptions || {}).response_type ||
          config.callbackOnLocationHash ? 'token' : 'code',
          params: config.internalOptions
     },
...
```
